#ifndef INCLUDE_GUARD__CAMERA_CAPTURE_H
#define INCLUDE_GUARD__CAMERA_CAPTURE_H

#include <stdint.h>

#define CAM_SENTENCE_LEN    67

// Note: 23 sentences is too few. 100 sometimes is too few. 250 is a good number, I think.
#define CAM_SENTENCES_PER_HALF_CALLBACK 250

#define CAM_BYTES_TO_RECEIVE_PER_HALF_CALLBACK ((CAM_SENTENCE_LEN) * (CAM_SENTENCES_PER_HALF_CALLBACK))


void CAM_repeated_error_log_message();


typedef enum CAM_capture_status_enum {
    CAM_CAPTURE_STATUS_TRANSMIT_SUCCESS,
    CAM_CAPTURE_STATUS_WRONG_INPUT,
    CAM_CAPTURE_STATUS_LFS_NOT_MOUNTED,
    CAM_CAPTURE_STATUS_LFS_FAILED_OPENING_CREATING_FILE,
    CAM_CAPTURE_STATUS_LFS_FAILED_WRITING_HEADER,
    CAM_CAPTURE_STATUS_FAILED_TRANSMITTING_LIGHTING_MODE,
    CAM_CAPTURE_STATUS_LFS_FAILED_CLOSING_FILE,
    CAM_CAPTURE_STATUS_CAPTURE_FAILURE,
} CAM_capture_status_enum;


CAM_capture_status_enum CAM_capture_image(char filename_str[], char lighting_mode);

#endif // INCLUDE_GUARD__CAMERA_CAPTURE_H
