/*
 * adcs_ids.h
 *
 *  Created on: Apr 30, 2024
 *      Author: Nadeem Moosa, Saksham Puri, Zachary Uy
 */

#ifndef INC_ADCS_IDS_H_
#define INC_ADCS_IDS_H_

/* Command IDs */

// Common Telecommand IDs - Section 6.1.1 Table 9 of Firmware Manual
static const uint8_t ADCS_COMMAND_RESET = 1; // must be followed by ADCS_MAGIC_NUMBER to confirm reset
static const uint8_t ADCS_COMMAND_RESET_LOG_POINTER = 4;
static const uint8_t ADCS_COMMAND_ADVANCE_LOG_POINTER = 5;
static const uint8_t ADCS_COMMAND_RESET_BOOT_REGISTERS = 6;
static const uint8_t ADCS_COMMAND_FORMAT_SD = 33;  // must be followed by ADCS_MAGIC_NUMBER to confirm format
static const uint8_t ADCS_COMMAND_ERASE_FILE = 108;
static const uint8_t ADCS_COMMAND_LOAD_FILE_DOWNLOAD_BLOCK = 112;
static const uint8_t ADCS_COMMAND_ADVANCE_FILELIST_READ_PTR = 113;
static const uint8_t ADCS_COMMAND_INIT_FILE_UPLOAD = 114;
static const uint8_t ADCS_COMMAND_FILE_UPLOAD_PACKET = 115;
static const uint8_t ADCS_COMMAND_FINALIZE_UPLOAD_BLOCK = 116;
static const uint8_t ADCS_COMMAND_RESET_UPLOAD_BLOCK = 117;
static const uint8_t ADCS_COMMAND_RESET_FILELIST_READ_PTR = 118;
static const uint8_t ADCS_COMMAND_INIT_DOWNLOAD_BURST = 119;

// Common Telemetry Frame IDs - Section 6.1.2 Table 26 of Firmware Manual
static const uint8_t ADCS_TELEMETRY_IDENTIFICATION = 128;
static const uint8_t ADCS_TELEMETRY_BOOT_RUNNING_PROGRAM_STATUS = 129;
static const uint8_t ADCS_TELEMETRY_BOOT_INDEX_STATUS = 130;
static const uint8_t ADCS_TELEMETRY_LAST_LOGGED_EVENT = 141;
static const uint8_t ADCS_TELEMETRY_FORMAT_SD = 234;
static const uint8_t ADCS_TELEMETRY_COMMAND_ACK = 240;
static const uint8_t ADCS_TELEMETRY_FILE_DOWNLOAD_BUFFER = 241;
static const uint8_t ADCS_TELEMETRY_DOWNLOAD_BLOCK_READY = 242;
static const uint8_t ADCS_TELEMETRY_FILE_INFO = 243;
static const uint8_t ADCS_TELEMETRY_INIT_UPLOAD_COMPLETE = 244;
static const uint8_t ADCS_TELEMETRY_UPLOAD_BLOCK_COMPLETE = 245;
static const uint8_t ADCS_TELEMETRY_BLOCK_CHECKSUM = 246;
static const uint8_t ADCS_TELEMETRY_SATSTATE_SRAM_LATCHUP_COUNTERS = 142;
static const uint8_t ADCS_TELEMETRY_SATSTATE_EDAC_ERROR_COUNTERS = 143;
static const uint8_t ADCS_TELEMETRY_SATSTATE_COMM_STATUS = 144;

// CubeACP Telecommand IDs - Section 5.3.1 Table 72 of Firmware Manual
static const uint8_t ADCS_COMMAND_DEPLOY_MAGNETOMETER_BOOM = 7;
static const uint8_t ADCS_COMMAND_ADCS_RUN_MODE = 10;
static const uint8_t ADCS_COMMAND_CLEAR_ERRORS = 12;
static const uint8_t ADCS_COMMAND_SET_ATTITUDE_CONTROL_MODE = 13;
static const uint8_t ADCS_COMMAND_SET_ATTITUDE_ESTIMATION_MODE = 14;
static const uint8_t ADCS_COMMAND_TRIGGER_ADCS_LOOP = 18;
static const uint8_t ADCS_COMMAND_TRIGGER_ADCS_LOOP_WITH_SIMULATED_SENSOR_DATA = 19;
static const uint8_t ADCS_COMMAND_ASGP4_RUN_MODE = 31;
static const uint8_t ADCS_COMMAND_ASGP4_TRIGGER = 32;
static const uint8_t ADCS_COMMAND_SET_MODE_OF_MAGNETOMETER_OPERATION = 56;
static const uint8_t ADCS_COMMAND_CONVERT_TO_JPG_FILE = 57;
static const uint8_t ADCS_COMMAND_SAVE_IMAGE = 80;
static const uint8_t ADCS_COMMAND_SET_MAGNETORQUER_OUTPUT = 16;
static const uint8_t ADCS_COMMAND_SET_WHEEL_SPEED = 17;
static const uint8_t ADCS_COMMAND_SAVE_CONFIG = 63;
static const uint8_t ADCS_COMMAND_SAVE_ORBIT_PARAMS = 64;

// Common Configuration Messages - Section 6.1.3 Table 47 of Firmware Manual
static const uint8_t ADCS_COMMAND_SET_CACHE_ENABLED_STATE = 3;
static const uint8_t ADCS_TELEMETRY_GET_CACHE_ENABLED_STATE = 131;
static const uint8_t ADCS_COMMAND_SET_SRAM_SCRUB_PARAMETERS = 8;
static const uint8_t ADCS_TELEMETRY_GET_SRAM_SCRUB_PARAMETERS = 134;
static const uint8_t ADCS_COMMAND_SET_UNIX_TIME_SAVE_TO_FLASH = 9;
static const uint8_t ADCS_TELEMETRY_GET_UNIX_TIME_SAVE_TO_FLASH = 145;
static const uint8_t ADCS_COMMAND_SET_HOLE_MAP_1 = 120;
static const uint8_t ADCS_TELEMETRY_GET_HOLE_MAP_1 = 247;
static const uint8_t ADCS_COMMAND_SET_HOLE_MAP_2 = 121;
static const uint8_t ADCS_TELEMETRY_GET_HOLE_MAP_2 = 248;
static const uint8_t ADCS_COMMAND_SET_HOLE_MAP_3 = 122;
static const uint8_t ADCS_TELEMETRY_GET_HOLE_MAP_3 = 249;
static const uint8_t ADCS_COMMAND_SET_HOLE_MAP_4 = 123;
static const uint8_t ADCS_TELEMETRY_GET_HOLE_MAP_4 = 250;
static const uint8_t ADCS_COMMAND_SET_HOLE_MAP_5 = 124;
static const uint8_t ADCS_TELEMETRY_GET_HOLE_MAP_5 = 251;
static const uint8_t ADCS_COMMAND_SET_HOLE_MAP_6 = 125;
static const uint8_t ADCS_TELEMETRY_GET_HOLE_MAP_6 = 252;
static const uint8_t ADCS_COMMAND_SET_HOLE_MAP_7 = 126;
static const uint8_t ADCS_TELEMETRY_GET_HOLE_MAP_7 = 253;
static const uint8_t ADCS_COMMAND_SET_HOLE_MAP_8 = 127;
static const uint8_t ADCS_TELEMETRY_GET_HOLE_MAP_8 = 254;
static const uint8_t ADCS_COMMAND_SET_CURRENT_UNIX_TIME = 2;
static const uint8_t ADCS_TELEMETRY_GET_CURRENT_UNIX_TIME = 140;

// CubeACP Telemetry Frames - Section 6.3.2 Table 97 of Firmware Manual
static const uint8_t ADCS_TELEMETRY_CUBEACP_ADCS_STATE = 132;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ESTIMATED_ATTITUDE_ANGLES = 146;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ESTIMATED_ANGULAR_RATES = 147;
static const uint8_t ADCS_TELEMETRY_CUBEACP_SATELLITE_POSITION_ECI = 148;
static const uint8_t ADCS_TELEMETRY_CUBEACP_SATELLITE_VELOCITY_ECI = 149;
static const uint8_t ADCS_TELEMETRY_CUBEACP_SATELLITE_POSITION_LLH = 150;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ADCS_STATE_2 = 190;
static const uint8_t ADCS_TELEMETRY_CUBEACP_FINE_ESTIMATED_ANGULAR_RATES = 201;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ESTIMATED_QUATERNION = 218;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ECEF_POSITION = 219;
static const uint8_t ADCS_TELEMETRY_CUBEACP_CURRENT_ADCS_STATE_2 = 224;
static const uint8_t ADCS_TELEMETRY_CUBEACP_JPG_CONVERSION_PROGRESS = 133;
static const uint8_t ADCS_TELEMETRY_CUBEACP_CUBEACP_STATE = 135;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ADCS_EXECUTION_TIMES = 196;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ACP_EXECUTION_STATE = 220;
static const uint8_t ADCS_TELEMETRY_CUBEACP_IMAGE_CAPTURE_AND_SAVE_STATUS = 233;
static const uint8_t ADCS_TELEMETRY_CUBEACP_MAGNETIC_FIELD_VECTOR = 151;
static const uint8_t ADCS_TELEMETRY_CUBEACP_COARSE_SUN_VECTOR = 152;
static const uint8_t ADCS_TELEMETRY_CUBEACP_FINE_SUN_VECTOR = 153;
static const uint8_t ADCS_TELEMETRY_CUBEACP_NADIR_VECTOR = 154;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RATE_SENSOR_RATES = 155;
static const uint8_t ADCS_TELEMETRY_CUBEACP_WHEEL_SPEED = 156;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_1_BODY_VECTOR = 181;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_2_BODY_VECTOR = 182;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_3_BODY_VECTOR = 183;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_1_ORBIT_VECTOR = 184;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_2_ORBIT_VECTOR = 185;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_3_ORBIT_VECTOR = 186;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ADCS_MEASUREMENTS = 191;
static const uint8_t ADCS_TELEMETRY_CUBEACP_MAGNETORQUER_COMMAND = 157;
static const uint8_t ADCS_TELEMETRY_CUBEACP_WHEEL_SPEED_COMMANDS = 158;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ACTUATOR_COMMANDS = 192;
static const uint8_t ADCS_TELEMETRY_CUBEACP_IGRF_MODELLED_MAGNETIC_FIELD_VECTOR = 159;
static const uint8_t ADCS_TELEMETRY_CUBEACP_MODELLED_SUN_VECTOR = 160;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ESTIMATED_GYRO_BIAS = 161;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ESTIMATION_INNOVATION_VECTOR = 162;
static const uint8_t ADCS_TELEMETRY_CUBEACP_QUATERNION_ERROR_VECTOR = 163;
static const uint8_t ADCS_TELEMETRY_CUBEACP_QUATERNION_COVARIANCE = 164;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ANGULAR_RATE_COVARIANCE = 165;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ESTIMATION_DATA = 193;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ASGP4_TLES = 228;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_CAM2_SENSOR = 166;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_CAM1_SENSOR = 167;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_CSS_1_TO_6 = 168;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_CSS_7_TO_10 = 169;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_MAGNETOMETER = 170;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_GPS_STATUS = 176;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_GPS_TIME = 177;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_GPS_X = 178;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_GPS_Y = 179;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_GPS_Z = 180;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_MAGNITUDE = 187;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_PERFORMANCE_1 = 188;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_TIMING = 189;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_SENSOR_MEASUREMENTS = 194;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_GPS_MEASUREMENTS = 210;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_STAR_TRACKER = 211;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_1_RAW_DATA = 212;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_2_RAW_DATA = 213;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_3_RAW_DATA = 214;
static const uint8_t ADCS_TELEMETRY_CUBEACP_SECONDARY_MAGNETOMETER_RAW_MEASUREMENTS = 215;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RAW_RATE_SENSOR = 216;
static const uint8_t ADCS_TELEMETRY_CUBEACP_CUBESTAR_ESTIMATED_RATES = 229;
static const uint8_t ADCS_TELEMETRY_CUBEACP_CUBESTAR_ESTIMATED_QUATERNION = 230;
static const uint8_t ADCS_TELEMETRY_CUBEACP_STAR_PERFORMANCE_2 = 231;
static const uint8_t ADCS_TELEMETRY_CUBEACP_CUBESENSE1_CURRENT_MEASUREMENTS = 171;
static const uint8_t ADCS_TELEMETRY_CUBEACP_CUBECONTROL_CURRENT_MEASUREMENTS = 172;
static const uint8_t ADCS_TELEMETRY_CUBEACP_WHEEL_CURRENTS_XYZ = 173;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ADCS_TEMPERATURES = 174;
static const uint8_t ADCS_TELEMETRY_CUBEACP_RATE_SENSOR_TEMPERATURES = 175;
static const uint8_t ADCS_TELEMETRY_CUBEACP_POWER_AND_TEMPERATURE_MEASUREMENTS = 195;
static const uint8_t ADCS_TELEMETRY_CUBEACP_ADCS_MISC_CURRENT_MEASUREMENTS = 198;
static const uint8_t ADCS_TELEMETRY_CUBEACP_CUBESENSE2_CURRENT_MEASUREMENTS = 232;

// CubeACP Configuration Messages - Section 6.3.3 Table 178 of Firmware Manual
static const uint8_t ADCS_COMMAND_CUBEACP_SET_MAGNETORQUER_CONFIG = 21;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_MAGNETORQUER_CONFIG = 136;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_WHEEL_CONFIG = 22;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_WHEEL_CONFIG = 137;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_RATE_GYRO_CONFIG = 23;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_RATE_GYRO_CONFIG = 138;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_CSS_CONFIG = 24;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_CSS_CONFIG = 139;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_STAR_TRACKER_CONFIG = 37;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_STAR_TRACKER_CONFIG = 202;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_CUBESENSE_CONFIG = 25;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_CUBESENSE_CONFIG = 203;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_MAGNETOMETER_CONFIG = 26;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_MAGNETOMETER_CONFIG = 204;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_REDUNDANT_MAGNETOMETER_CONFIG = 36;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_REDUNDANT_MAGNETOMETER_CONFIG = 205;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_ADCS_CONFIG = 20;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_ADCS_CONFIG = 206;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_SGP4_ORBIT_PARAMETERS = 45;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_SGP4_ORBIT_PARAMETERS = 207;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_DETUMBLING_CONTROL_PARAMETERS = 38;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_DETUMBLING_CONTROL_PARAMETERS = 208;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_Y_WHEEL_CONTROL_PARAMETERS = 39;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_Y_WHEEL_CONTROL_PARAMETERS = 209;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_REACTION_WHEEL_CONTROL_PARAMETERS = 40;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_REACTION_WHEEL_CONTROL_PARAMETERS = 217;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_TRACKING_CONTROLLER_GAIN_PARAMETERS = 54;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_TRACKING_CONTROLLER_GAIN_PARAMETERS = 221;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_MOMENT_OF_INERTIA_MATRIX = 41;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_MOMENT_OF_INERTIA_MATRIX = 222;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_ESTIMATION_PARAMETERS = 27;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_ESTIMATION_PARAMETERS = 223;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_ADCS_SYSTEM_CONFIG = 30;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_ADCS_SYSTEM_CONFIG = 225;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_USER_CODED_CONTROLLER_AND_ESTIMATOR_PARAMETERS = 29;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_USER_CODED_CONTROLLER_AND_ESTIMATOR_PARAMETERS = 226;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_AUGMENTED_SGP4_PARAMETERS = 28;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_AUGMENTED_SGP4_PARAMETERS = 227;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_ADCS_POWER_CONTROL = 11;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_ADCS_POWER_CONTROL = 197;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_COMMANDED_ATTITUDE_ANGLES = 15;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_COMMANDED_ATTITUDE_ANGLES = 199;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_TRACKING_CONTROLLER_TARGET_REFERENCE = 55;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_TRACKING_CONTROLLER_TARGET_REFERENCE = 200;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_SD_LOG1_CONFIG = 104;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_SD_LOG1_CONFIG = 235;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_SD_LOG2_CONFIG = 105;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_SD_LOG2_CONFIG = 236;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_UART_LOG_CONFIG = 106;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_UART_LOG_CONFIG = 237;
static const uint8_t ADCS_COMMAND_CUBEACP_SET_INERTIAL_POINTING_REFERENCE_VECTOR = 34;
static const uint8_t ADCS_TELEMETRY_CUBEACP_GET_INERTIAL_POINTING_REFERENCE_VECTOR = 238;

// Bootloader Telecommand IDs - Section 6.2.1 Table 60 of Firmware Manual
static const uint8_t ADCS_COMMAND_BOOTLOADER_CLEAR_ERRORS = 7;
static const uint8_t ADCS_COMMAND_BOOTLOADER_SET_INDEX = 100;
static const uint8_t ADCS_COMMAND_BOOTLOADER_RUN_PROGRAM = 101;
static const uint8_t ADCS_COMMAND_BOOTLOADER_READ_INFO = 102;
static const uint8_t ADCS_COMMAND_BOOTLOADER_COPY_TO_FLASH = 103;

#endif /* INC_ADCS_IDS_H_ */