#ifndef __INCLUDE_GUARD__TEST_LOGGING_H__
#define __INCLUDE_GUARD__TEST_LOGGING_H__

#include <stdint.h>

uint8_t TEST_EXEC__LOG_enable_disable_LOG_CHANNEL_FILE(void);
uint8_t TEST_EXEC__LOG_enable_disable_LOG_CHANNEL_UHF_RADIO(void);
uint8_t TEST_EXEC__LOG_enable_disable_LOG_CHANNEL_UMBILICAL_UART(void);
uint8_t TEST_EXEC__LOG_enable_disable_LOG_FILE_LOGGING_FOR_SYSTEM_MPI(void);
uint8_t TEST_EXEC__LOG_all_channels_except(void);
uint8_t TEST_EXEC__LOG_message(void);

#endif // __INCLUDE_GUARD__TEST_LOGGING_H__
