#ifndef INCLUDE_GUARD__TEST_TEMPERATURE_SENSOR_H__
#define INCLUDE_GUARD__TEST_TEMPERATURE_SENSOR_H__

#include <stdint.h>

uint8_t TEST_EXEC__OBC_TEMP_SENSOR_convert_raw_to_deg_c(void);
uint8_t TEST_EXEC__OBC_TEMP_SENSOR_configure_precision_values(void);

#endif // INCLUDE_GUARD__TEST_TEMPERATURE_SENSOR_H__