
#ifndef INCLUDE_GUARD__STM32_REBOOT_REASON_H
#define INCLUDE_GUARD__STM32_REBOOT_REASON_H

/// @brief  Possible STM32 system reset causes
typedef enum STM32_reset_cause_e
{
    STM32_RESET_CAUSE_UNKNOWN = 0,
    STM32_RESET_CAUSE_LOW_POWER_RESET,
    STM32_RESET_CAUSE_WINDOW_WATCHDOG_RESET,
    STM32_RESET_CAUSE_INDEPENDENT_WATCHDOG_RESET,
    STM32_RESET_CAUSE_SOFTWARE_RESET,
    STM32_RESET_CAUSE_EXTERNAL_RESET_PIN_RESET,
    STM32_RESET_CAUSE_BROWNOUT_RESET,
    STM32_RESET_CAUSE_OPTION_BYTE_LOADER_RESET,
    STM32_RESET_CAUSE_FIREWALL_RESET,
} STM32_reset_cause_t;

STM32_reset_cause_t STM32_get_reset_cause(void);
char * STM32_reset_cause_enum_to_str(STM32_reset_cause_t reset_cause);

#endif // INCLUDE_GUARD__STM32_REBOOT_REASON_H
