#ifndef INCLUDE_GUARD__START_OF_MISSION_PROCEDURE_H
#define INCLUDE_GUARD__START_OF_MISSION_PROCEDURE_H

#include <stdint.h>

uint32_t DETECT_tumble();

#endif /* INCLUDE_GUARD__MISSION_PROCEDURE_H */