target := "thumbv7em-none-eabihf"
build_dir := "build"
project_name := "demo_rust_blob_1"

# Show available commands.
default:
    @just --list

# Show available commands.
help:
    @just --list

# Build the elf file from Rust source with Cargo.
elf:
    mkdir -p {{build_dir}}
    cargo build --release
    cp target/{{target}}/release/{{project_name}} {{build_dir}}/{{project_name}}.elf

# MAIN: Convert the elf file to a binary file, and show its size.
build: elf
    arm-none-eabi-objcopy -O binary {{build_dir}}/{{project_name}}.elf {{build_dir}}/{{project_name}}.bin
    arm-none-eabi-size {{build_dir}}/{{project_name}}.elf
    sha256sum {{build_dir}}/{{project_name}}.bin
    du --bytes {{build_dir}}/{{project_name}}.bin

clean:
    cargo clean
    rm -rf {{build_dir}}
