#ifndef INC_ADCS_STRUCT_PACKERS_H_
#define INC_ADCS_STRUCT_PACKERS_H_

#include "adcs_drivers/adcs_types.h"

// ADCS packer functions
uint8_t ADCS_Pack_to_Ack_Struct(uint8_t* data_received, ADCS_cmd_ack_struct_t *result);
uint8_t ADCS_Pack_to_Identification_Struct(uint8_t* data_received, ADCS_id_struct_t *result);
uint8_t ADCS_Pack_to_Program_Status_Struct(uint8_t* data_received, ADCS_boot_running_status_struct_t *result);
uint8_t ADCS_Pack_to_Comms_Status_Struct(uint8_t* data_received, ADCS_comms_status_struct_t *result);
uint8_t ADCS_Pack_to_Power_Control_Struct(uint8_t* data_received, ADCS_power_control_struct_t *result);
uint8_t ADCS_Pack_to_Angular_Rates_Struct(uint8_t* data_received, ADCS_angular_rates_struct_t *result);
uint8_t ADCS_Pack_to_LLH_Position_Struct(uint8_t* data_received, ADCS_llh_position_struct_t *result);
uint8_t ADCS_Pack_to_Unix_Time_Save_Mode_Struct(uint8_t* data_received, ADCS_set_unix_time_save_mode_struct_t *result);
uint8_t ADCS_Pack_to_Orbit_Params_Struct(uint8_t* data_received, ADCS_orbit_params_struct_t *result);
uint8_t ADCS_Pack_to_Rated_Sensor_Rates_Struct(uint8_t* data_received, ADCS_rated_sensor_rates_struct_t *result);
uint8_t ADCS_Pack_to_Wheel_Speed_Struct(uint8_t* data_received, ADCS_wheel_speed_struct_t *result);
uint8_t ADCS_Pack_to_Magnetorquer_Command_Struct(uint8_t* data_received, ADCS_magnetorquer_command_struct_t *result);
uint8_t ADCS_Pack_to_Raw_Magnetometer_Values_Struct(uint8_t* data_received, ADCS_raw_magnetometer_values_struct_t *result);
uint8_t ADCS_Pack_to_Fine_Angular_Rates_Struct(uint8_t* data_received, ADCS_fine_angular_rates_struct_t *result);
uint8_t ADCS_Pack_to_Magnetometer_Config_Struct(uint8_t* data_received, ADCS_magnetometer_config_struct_t *result);
uint8_t ADCS_Pack_to_Commanded_Attitude_Angles_Struct(uint8_t* data_received, ADCS_commanded_angles_struct_t *result);
uint8_t ADCS_Pack_to_Estimation_Params_Struct(uint8_t* data_received, ADCS_estimation_params_struct_t *result);
uint8_t ADCS_Pack_to_Augmented_SGP4_Params_Struct(uint8_t* data_received, ADCS_augmented_sgp4_params_struct_t *result);
uint8_t ADCS_Pack_to_Tracking_Controller_Target_Reference_Struct(uint8_t* data_received, ADCS_tracking_controller_target_struct_t *result);
uint8_t ADCS_Pack_to_Rate_Gyro_Config_Struct(uint8_t* data_received, ADCS_rate_gyro_config_struct_t *result);
uint8_t ADCS_Pack_to_Estimated_Attitude_Angles_Struct(uint8_t *data_received, ADCS_estimated_attitude_angles_struct_t *angles);
uint8_t ADCS_Pack_to_Magnetic_Field_Vector_Struct(uint8_t *data_received, ADCS_magnetic_field_vector_struct_t *vector_components);
uint8_t ADCS_Pack_to_Fine_Sun_Vector_Struct(uint8_t *data_received, ADCS_fine_sun_vector_struct_t *vector_components);
uint8_t ADCS_Pack_to_Nadir_Vector_Struct(uint8_t *data_received, ADCS_nadir_vector_struct_t *vector_components);
uint8_t ADCS_Pack_to_Commanded_Wheel_Speed_Struct(uint8_t *data_received, ADCS_wheel_speed_struct_t *result);
uint8_t ADCS_Pack_to_IGRF_Magnetic_Field_Vector_Struct(uint8_t *data_received, ADCS_magnetic_field_vector_struct_t *vector_components);
uint8_t ADCS_Pack_to_Quaternion_Error_Vector_Struct(uint8_t *data_received, ADCS_quaternion_error_vector_struct_t *result);
uint8_t ADCS_Pack_to_Estimated_Gyro_Bias_Struct(uint8_t* data_received, ADCS_estimated_gyro_bias_struct_t *result);
uint8_t ADCS_Pack_to_Estimation_Innovation_Vector_Struct(uint8_t* data_received, ADCS_estimation_innovation_vector_struct_t *result);
uint8_t ADCS_Pack_to_Raw_Cam1_Sensor_Struct(uint8_t* data_received, ADCS_raw_cam_sensor_struct_t *result);
uint8_t ADCS_Pack_to_Raw_Cam2_Sensor_Struct(uint8_t* data_received, ADCS_raw_cam_sensor_struct_t *result);
uint8_t ADCS_Pack_to_Raw_Coarse_Sun_Sensor_1_to_6_Struct(uint8_t* data_received, ADCS_raw_coarse_sun_sensor_1_to_6_struct_t *result);
uint8_t ADCS_Pack_to_Raw_Coarse_Sun_Sensor_7_to_10_Struct(uint8_t* data_received, ADCS_raw_coarse_sun_sensor_7_to_10_struct_t *result);
uint8_t ADCS_Pack_to_CubeControl_Current_Struct(uint8_t* data_received, ADCS_cubecontrol_current_struct_t *result);
uint8_t ADCS_Pack_to_Raw_GPS_Status_Struct(uint8_t* data_received, ADCS_raw_gps_status_struct_t *result);
uint8_t ADCS_Pack_to_Raw_GPS_Time_Struct(uint8_t* data_received, ADCS_raw_gps_time_struct_t *result);
uint8_t ADCS_Pack_to_Raw_GPS_Struct(ADCS_gps_axis_enum_t axis, uint8_t *data_received, ADCS_raw_gps_struct_t *result);
uint8_t ADCS_Pack_to_Measurements_Struct(uint8_t* telemetry_data, ADCS_measurements_struct_t *measurements);
uint8_t ADCS_Pack_to_ACP_Execution_State_Struct(uint8_t* data_received, ADCS_acp_execution_state_struct_t* output_struct);

#endif /* INC_ADCS_STRUCT_PACKERS_H_ */