name: Run Python Unit Tests via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e cts1_ground_support[dev]
      - name: Lint with Ruff
        run: |
          ruff check cts1_ground_support/
        # continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest cts1_ground_support/tests -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
