name: Tests and Checks

on: [push]

jobs:
  c-firmware-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup C build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc-arm-none-eabi
      
      - name: Build C firmware
        working-directory: firmware
        run: |
          make -f Makefile.GitHub.mk

      - name: Dump repo size/file count stats
        run: |
          pwd
          echo "Number of files in the firmware directory:"
          du -a firmware | wc -l
          echo "Total number of files in the repo:"
          du -a | wc -l
          echo "Size of the main sections of this project:"
          du -sh *
        # TODO: add line count stats in here for fun

      - name: Ensure build was successful (artifact exists)
        run: |
          ls -l ./firmware/build/CTS-SAT-1_FW.elf

  python-linting-and-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e cts1_ground_support[dev]
      - name: Lint with Ruff
        run: |
          ruff version
          ruff check cts1_ground_support/
        # continue-on-error: true
      - name: Test with pytest
        run: |
          coverage run -m pytest cts1_ground_support/tests -v -s
      - name: Generate Coverage Report
        run: |
          coverage report -m
  
  validate-telecommand-structs-and-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e cts1_ground_support[dev]
      - name: Check Telecommand Structs and Docs
        run: |
          python ./cts1_ground_support/firmware_checks/_01_check_tcmd_structs_and_docs.py
