name: Tests and Checks

on: [push]

jobs:
  c-firmware-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup C build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc-arm-none-eabi

      - name: Print C compiler version
        run: |
          arm-none-eabi-gcc --version
      
      - name: Build C firmware
        working-directory: firmware
        run: |
          make -f Makefile.GitHub.mk

      - name: Dump repo size/file count stats
        run: |
          pwd
          echo "Number of files in the firmware directory:"
          du -a firmware | wc -l
          echo "Total number of files in the repo:"
          du -a | wc -l
          echo "Size of the main sections of this project:"
          du -sh *
        # TODO: add line count stats in here for fun

      - name: Ensure build was successful (check ELF artifact exists)
        run: |
          ls -l ./firmware/build/CTS-SAT-1_FW.elf
  
  validate-telecommand-structs-and-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./firmware_checks/requirements.txt
      - name: Check Telecommand Structs and Docs
        run: |
          python ./firmware_checks/_01_check_tcmd_structs_and_docs.py
      - name: Check C Unit Test Inventory
        run: |
          python ./firmware_checks/_02_check_c_unit_test_inventory.py
      - name: Check for Missing Telecommand Registrations
        run: |
          python ./firmware_checks/_03_check_missing_tcmd_registrations.py
          